name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.9'
    - run: go version
    - name: install build packages (general)
      run: sudo apt-get install ruby ruby-dev build-essential rpm
    - name: install build packages (Ruby Gem)
      run: gem install --no-ri --no-rdoc fpm
    - name: fetch dependencies
      run: go get -d ./...
#     - name: dep ensure
#       run: dep ensure
#    - name: run unit tests
#      run: make test
    - name: make build
      run: make build
